In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6"  color="red">ch10. N차원 배열(Numpy) </font></b>
 
# 4절 복사와 뷰
## 4.1 할당

In [5]:
# numpy 배열
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
b=a


In [8]:
a.shape,a.ndim,id(a),type(a)

((12,), 1, 2005663313296, numpy.ndarray)

In [9]:
b.shape,b.ndim,id(b),type(b)

((12,), 1, 2005663313296, numpy.ndarray)

In [10]:
a is b

True

In [11]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [13]:
np.all(a==b)

True

### **할당

In [14]:
b.shape=(3,4) # 할당받은 b의 shape을 수정

In [15]:
a.shape,a.ndim,id(a),type(a)

((3, 4), 2, 2005663313296, numpy.ndarray)

In [16]:
b.shape,b.ndim,id(b),type(b)

((3, 4), 2, 2005663313296, numpy.ndarray)

## 4.2 얕은복사 : 뷰(View)

In [18]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [27]:
c=a.copy()             # 깊은복사
print(a,c,id(a),id(c))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2005697508240 2005725482704


In [36]:
c=a.view()            # 얕은복사
print(a,c,id(a),id(c))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2005697508240 2005725483184


In [37]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
c[1,::2] = -99 # 1행의 짝수번째 열 변경(9)
c

array([[  0,   1,   2,   3,   4,   5],
       [-99,   7, -99,   9, -99,  11]])

In [45]:
a

array([[  0,   1,   2,   3],
       [  4,   5, -99,   7],
       [-99,   9, -99,  11]])

## 4.3 깊은 복사

In [61]:
a = np.array([[5,  4, 13, 0],
              [90, 6, 16, 1],
              [20, 5, 14, 0]])
a

array([[ 5,  4, 13,  0],
       [90,  6, 16,  1],
       [20,  5, 14,  0]])

###  **<font color=red>(주의)</font>슬라이싱이 될 때, 뷰가 반환됨(얕은)

In [62]:
#X = a[:, :-1]   # 슬라이싱이 될 때, 뷰가 반환됨(얕은)
X = a[:, :-1].copy() #깊은복사
X = np.array(a[:,:-1],copy=True)  #깊은복사
X

array([[ 5,  4, 13],
       [90,  6, 16],
       [20,  5, 14]])

In [63]:
X[:, 0] = -9
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [64]:
a

array([[ 5,  4, 13,  0],
       [90,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절 고급 인덱싱